### ISSUE TITLE
Fix hot reloading of config

### ISSUE THREAD

**Issue by nullpixel** [dynasticdevelop/place#189]
Results in `Cannot GET /` error.

**Comment by EricRabil** [comment]
I can look into this tonight, will try to push out a fix for it.

**Comment by AppleBetas** [comment]
I know why this happens. It waits for module manager to load before adding routes back to the HTTP server, and when changing OAuth config, the HTTP server is restarted, but routes aren't properly added back because module manager is already loaded. I believe the convenience function `fireWhenLoaded` on `ModuleManager` will fire the callback immediately if already loaded, so you could just move that to the `recreateServer` function in `app.js`.
