### ISSUE TITLE
Rehaul interactions for desktop & mobile

### ISSUE THREAD

**Issue by toficofi** [dynasticdevelop/place#34]

**Comment by toficofi** [comment]
I'll take this tonight

**Comment by toficofi** [comment]
About 50% complete. Will have it finished by tomorrow night.
- Smooth panning with inertia & bounds checking
- Tap-to-zoom & pinch-to-zoom with arbitrary zoom levels
- Drag'n'drop for colours instead of click'n'pick

**Comment by toficofi** [comment]
Got some smooth panning & zooming w/ pinch-to-zoom done in https://github.com/Jishaxe/place/commit/de7a090752f0fd592669a8900c309d756d3b474b, but I've not got time to integrate it with the newest changes atm I'll have to revisit later

**Comment by Two-Tone** [comment]
Not sure if I should suggest this here or not since it seems to be a meta bug report.

But an enhancement on Desktop I'd like to see is scrolling in and out with the scroll wheel.

Another, general enhancement I'd like to see is an *undo* button for the last pixel placed. Give it like a 5 - 10 second timer, if pressed within the first 5 - 10 seconds of placing a pixel, undo that pixel.  It's not often, but almost all of us have at one point or another misplaced a pixel or did the wrong color. A short lived undo button would fix that.

**Comment by AppleBetas** [comment]
Any update?

**Comment by nullpixel** [comment]
Only thing left to do here is smooth / scroll wheel zoom, #100 did the rest
